
server:
  port: 2020

spring:
  application:
    name: greenhouse_system

  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.6.186:3306/greenhouse_system?characterEncoding=utf8&useSSL=false



# mybaits 模块配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.douzi.greenhouse_system.entity


#sql语句打印
logging:
  level:
    com:
      douzi:
        greenhouse_system:
          mapper: debug

